[General]
N = 2000000

; Все времена в наносекундах
t1 = 100
t2_start = 0
t2_end = 5000
t2_step = 100
t3 = 150
t4 = 50
t5 = 500
t6 = 3000
t7 = 500
delay_between_measurements = 100

[Rigol]
freq = 2870 * 1E6
gain = 24 #dBm111
